name    'palladius-logrotate'
version '1.0.0'
source  'https://github.com/palladius/puppet-logrotate'
license 'MIT'
summary 'Logrotate module with testing and travis'
description  'Manage logrotate on your servers with Puppet. Copied from rodjek and experimenting with tarvis and autotest :)'
project_page 'https://github.com/palladius/puppet-logrotate'
